前面我们看到如何对两个形状相同的`Tensor`做按元素运算。当对两个形状不同的`Tensor`按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。例如：

In [2]:
import torch
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(2,5).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[2],
        [3],
        [4]])
tensor([[3, 4],
        [4, 5],
        [5, 6]])
