我们可以使用`numpy()`和`from_numpy()`将`Tensor`和NumPy中的数组相互转换。但是需要注意的一点是：**这两个函数所产生的的`Tensor`和NumPy的数组共享内存**

# `Tensor`转NumPy

使用`numpy()`将`Tensor`转换成NumPy数组：

In [5]:
import torch
a = torch.ones(5)
b = a.numpy()
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


# NumPy数组转`Tensor`

使用`from_numpy`将NumPy数组转换成`Tensor`:

In [6]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


所有在CPU上的`Tensor`都支持与NumPy数组相互转换。

将NumPy数组转换成`Tensor`的常用方法还有一个：`torch.tensor()`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存

In [7]:
c = torch.tensor(a)
a += 1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
