# 算数操作
## 加法一

In [4]:
import torch
x=torch.empty(3,5)
y=torch.randn(3,5)
print(x+y)

tensor([[-1.3842,  0.5717,  2.1196,  1.3433,  0.3387],
        [ 2.5572,  0.9532,  0.9249, -1.5904,  0.3159],
        [ 1.5556,  0.0898, -1.0415, -0.0334, -0.4741]])


## 加法二

In [5]:
print(torch.add(x,y))

tensor([[-1.3842,  0.5717,  2.1196,  1.3433,  0.3387],
        [ 2.5572,  0.9532,  0.9249, -1.5904,  0.3159],
        [ 1.5556,  0.0898, -1.0415, -0.0334, -0.4741]])


## 加法三

In [6]:
result=torch.empty(3,5)
torch.add(x,y,out=result)
print(result)

tensor([[-1.3842,  0.5717,  2.1196,  1.3433,  0.3387],
        [ 2.5572,  0.9532,  0.9249, -1.5904,  0.3159],
        [ 1.5556,  0.0898, -1.0415, -0.0334, -0.4741]])


## 加法四 inplace

In [7]:
y.add_(x)
print(y)

tensor([[-1.3842,  0.5717,  2.1196,  1.3433,  0.3387],
        [ 2.5572,  0.9532,  0.9249, -1.5904,  0.3159],
        [ 1.5556,  0.0898, -1.0415, -0.0334, -0.4741]])


## 索引
我们还可以使用类似NumPy的索引操作来访问```Tensor```的一部分，需要注意的是：**索引出来的结果与元数据共享内存，即修改一个，另一个会跟着修改。**

In [8]:
print(x)
y=x[:,0]
y+=1
print(y)
print(x)

tensor([[9.2755e-39, 1.0837e-38, 8.4490e-39, 1.0561e-38, 8.4490e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39, 8.4490e-39, 1.0194e-38]])
tensor([9.2755e-39, 9.6429e-39, 9.0919e-39])


除了常用的索引选择数据之外，PyTorch还提供了一些高级的选择函数

index_select(input, dim, index)
masked_select(input, mask)
non_zero(input) 
gather(input, dim, index)

## 改变形状
用```view()```来改变```Tensor```的形状：

In [17]:
y = x.view(15)
z = x.view(-1,3)
print(x.size(),y.size(),z.size())

torch.Size([3, 5]) torch.Size([15]) torch.Size([5, 3])


**注意```view()```返回的新Tensor与源Tensor共享内存（其实是同一个tensor），即更改其中一个，另一个也会跟着改变。
顾名思义，view仅仅是改变了对这个张量的观察角度。***

所以如果我们想返回一个真正的新的副本（即不共享内存），PyTorch提供了一个```reshape()```函数可以改变形状，但是次函数不保证返回的是其拷贝，所以不推荐使用。推荐先用```clone```创造一个副本然后再使用```view```

In [19]:
x_cp=x.clone().view(15)
x -=1
print(x)
print(x_cp)

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


使用```clone```还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源```Tensor```中。

另外一个常用的函数是```item()```，它可以讲一个标量```Tensor```转换成Python Number：

In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3406])
0.34062474966049194


## 线性代数

<img src="Line.png">