因为out是一个标量，所以调用`backward()`时不需要指定求导变量：

In [11]:
import torch
x = torch.ones(2,2,requires_grad=True)
y = x + 2
z = y * y *3
out = z.mean()
out.backward()
print(out)
print(x.grad)


tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [13]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000]])
tensor([[1., 1.],
        [1., 1.]])


**我们不允许张量对向量求导，只允许标量对张量求导，求导结果是和自变量同形的张量**

In [23]:
x = torch.tensor([1.0,2.0,3.0,4.0],requires_grad = True)
y = 2 * x
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [24]:
v = torch.tensor([[1.,0.],[2.,4.]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2., 0., 4., 8.])


中断梯度追踪：

如果我们想要修改`tensor`的数值，但是又不希望被`autograd`记录（即：不影响反向传播），那么我们可以对`tensor.data`进行操作

In [30]:
x = torch.tensor([1.,2.,3.],requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x**3
y3 = y1 + y2

print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)
y3.backward(torch.tensor([1.,1.,1.]))
print(x.grad)

True
tensor([1., 4., 9.], grad_fn=<PowBackward0>) True
tensor([ 1.,  8., 27.]) False
tensor([ 2., 12., 36.], grad_fn=<AddBackward0>) True
tensor([2., 4., 6.])


In [33]:
x=torch.ones(1,requires_grad=True)

print(x.data)
print(x.data.requires_grad)

y = 2*x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


In [34]:
torch.cuda.is_available()

True