# 生成数据集

In [55]:
import numpy as np
import torch
num_inputs=2
num_examples=1000
true_w=[2,-1]
true_b=8
features=torch.tensor(np.random.normal(
    0, 1, (num_examples, num_inputs)),dtype=torch.float)
labels=true_w[0]*features[:, 0]+true_w[1]*features[:, 1]+ true_b
labels +=torch.tensor(np.random.normal(0, 0.01, size=labels.size()),dtype=torch.float)

# 读取数据

In [62]:
import torch.utils.data as Data
batch_size = 10
dataset = Data.TensorDataset(features,labels)
r"""Dataset wrapping tensors.
    Each sample will be retrieved by indexing tensors along the first dimension.
    Arguments:
        *tensors (Tensor): tensors that have the same size of the first dimension.
    """
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True, num_workers=2)

# 定义模型

In [57]:
from torch import nn
# class LinearNet(nn.Module):
#     def __init__(self,n_feature):
#         super(LinearNet,self).__init__()
#         self.linear=nn.Linear(n_feature, 1)
#     def forward(self,x):
#         y = self.linear(x)
#         return y
net = nn.Sequential(
    nn.Linear(num_inputs, 1)
    # 此处还可以传入其它层
    )

In [69]:
for patam in net.parameters():
    print(param)

Parameter containing:
tensor([[ 1.9999, -1.0004]], requires_grad=True)
Parameter containing:
tensor([8.0001], requires_grad=True)
Parameter containing:
tensor([0.5130], requires_grad=True)
Parameter containing:
tensor([0.5130], requires_grad=True)


# 初始化模型参数

In [64]:
from torch.nn import init
init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)

Parameter containing:
tensor([0.], requires_grad=True)

# 定义损失函数

In [65]:
loss = nn.MSELoss()

# 定义优化算法

In [74]:
import torch.optim as optim

optimizer = optim.ASGD(net.parameters(), lr=0.03)
print(optimizer)

ASGD (
Parameter Group 0
    alpha: 0.75
    lambd: 0.0001
    lr: 0.03
    t0: 1000000.0
    weight_decay: 0
)


# 训练模型

In [75]:
num_epochs = 10
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss:%f'% (epoch, l.item()))

epoch 1, loss:0.000091
epoch 2, loss:0.000087
epoch 3, loss:0.000076
epoch 4, loss:0.000038
epoch 5, loss:0.000055
epoch 6, loss:0.000094
epoch 7, loss:0.000086
epoch 8, loss:0.000135
epoch 9, loss:0.000140
epoch 10, loss:0.000265


In [81]:

for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 1.9983, -1.0002]], requires_grad=True)
Parameter containing:
tensor([7.9992], requires_grad=True)
